# Generated by Django 4.0.1 on 2022-01-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=15)),
                ('employee_name', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=18)),
            ],
        ),
    ]
